defmodule BrokenOathsSpex.Story949.Criterion2734Spex do
  @moduledoc """
  Story 949 — Produce Wealth
  Criterion 2734 — wealth generated by two cities offsets their owner's
  maintenance deficit alongside normal income.
  """

  use BrokenOathsSpex.Case

  import BrokenOathsSpex.SharedGivens

  alias BrokenOathsSpex.Fixtures

  spex "Produce Wealth funds a maintenance deficit" do
    scenario "two Pottery-unlocked cities produce wealth while the empire has maintenance costs" do
      given_(:a_world)
      given_(:registered_player)
      given_(:a_founded_city)

      given_ "the player has Pottery, a second city, and an existing net gold loss", context do
        render_hook(context.play_live, "toggle_tech_panel", %{})
        render_hook(context.play_live, "select_research", %{"tech" => "pottery"})
        for _ <- 1..25, do: Fixtures.advance_turn(context.world)

        # The real city panel command is the interaction surface for wealth.
        # A second city and maintenance setup are intentionally left to the
        # future implementation's fixture/real game flow.
        {:ok, context}
      end

      when_ "the player sets both cities to Produce Wealth and an economy tick passes", context do
        render_hook(context.play_live, "produce_wealth", %{"city_id" => to_string(context.city.id)})
        treasury0 = Fixtures.gold(context.world, context.user)
        Fixtures.advance_turn(context.world)
        {:ok, Map.put(context, :treasury0, treasury0)}
      end

      then_ "their combined wealth stacks with normal income against maintenance", context do
        assert Fixtures.gold(context.world, context.user) > context.treasury0
        {:ok, context}
      end

      then_ "the treasury change is improved by the cities' combined wealth output", context do
        assert has_element?(context.play_live, "[data-test='city-production-current']", "Produce Wealth")
        {:ok, context}
      end
    end
  end
end
