import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :broken_oaths, BrokenOathsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# No app-level force_ssl: kamal-proxy terminates TLS and redirects
# http -> https at the edge (proxy.ssl: true in config/deploy*.yml), and
# its plain-HTTP health probes must get a 200 from the app, not a 301.
# Same posture as the rest of the fleet.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
