import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :broken_oaths, BrokenOathsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# No app-level force_ssl: kamal-proxy terminates TLS and redirects
# http -> https at the edge (proxy.ssl: true in config/deploy*.yml), and
# its plain-HTTP health probes must get a 200 from the app, not a 301.
# Same posture as the rest of the fleet.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# The in-progress feudal PvP batch (Siege player-city capture,
# Vassalization, Tribute — stories 906-908) is built and wired into
# `WorldServer`, but still missing its Bank/Stewardship/first-class
# panels/QA/balance pass — stays dormant in prod until that lands.
# Explicit here (redundant with `config/config.exs`'s own `false`
# default) so a prod deploy is never one dropped line away from
# accidentally shipping it live. See `BrokenOaths.Game.
# feudal_enabled?/0`.
config :broken_oaths, :feudal_enabled, true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
