defmodule BrokenOaths.CmsUsers do
  @moduledoc """
  Read model for the application's registered users, exposed to the CodeMySpec
  dashboard via `BrokenOathsWeb.CmsUsersController`.

  Lives in the domain boundary so it may touch the Repo; the web layer must
  not. Generated by `mix client_utils.gen.cms_users` — safe to edit, but a
  re-run overwrites it.
  """

  import Ecto.Query, only: [from: 2]

  alias BrokenOaths.Repo
  alias BrokenOaths.Users.User

  @doc "Lists registered users for `page` (1-based, oldest first)."
  def list_registered_users(page, page_size) when page > 0 and page_size > 0 do
    offset = (page - 1) * page_size

    from(u in User,
      order_by: [asc: u.inserted_at],
      limit: ^page_size,
      offset: ^offset
    )
    |> Repo.all()
  end

  @doc "Total number of registered users."
  def count_registered_users do
    Repo.aggregate(User, :count, :id)
  end
end
